language: python
sudo: false
python:
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
script: QOTR_ENV=test nosetests --with-coverage --cover-package=qotr
after_success:
  - coveralls
